### ISSUE TITLE
optional format string

### ISSUE THREAD

**Issue by rbucker** [monder/rkt-sidekick#1]
The user provides a etcd key and the sidekick stores the IP address in that location, however, skyDNS uses a JSON formatted value that include a TTL. It would be helpful if the RUN command could include the format of the value in the go template format or  at least Printf() format string.

**Comment by monder** [comment]
I initially thought about it, because some services require to expose port number for example, but decided to go with simpler approach. :)
I've pushed the v0.0.2 version which supports `--format` flag and changed the example to be compatible with SkyDNS.
