### ISSUE TITLE
flannel and etcd setup

### ISSUE THREAD

**Issue by rbucker** [monder/rkt-sidekick#3]
would you please describe your flannel and etcd setup. Running etcd on the host and not within the flannel subnet is throwing errors.

**Comment by monder** [comment]
Hey,
I'm not sure if my setup is common, but I'm currently using this project on AWS with flannel in `aws-vpc` mode. So in that kind of sense everything is "in" flannel subnet.
What kind of errors are you getting? The default address `172.16.28.1` is the host machine's address in `default-restricted`. It will work if you have etcd on host listening on 0.0.0.0 and pod with any network + `default-restricted`.

```
core@ip-10-0-1-152 ~ $ sudo rkt run --insecure-options=image --net=flannel --interactive docker://busybox
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.10.1
image: using image from local store for url docker://busybox
networking: loading networks from /etc/rkt/net.d
networking: loading network flannel with type flannel
networking: loading network default-restricted with type ptp
/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.4.0.0        10.4.26.1       255.255.0.0     UG    0      0        0 eth0
10.4.26.0       *               255.255.255.0   U     0      0        0 eth0
172.16.28.0     172.16.28.1     255.255.255.0   UG    0      0        0 eth1
172.16.28.1     *               255.255.255.255 UH    0      0        0 eth1
/ # ping 172.16.28.1
PING 172.16.28.1 (172.16.28.1): 56 data bytes
64 bytes from 172.16.28.1: seq=0 ttl=64 time=0.122 ms
64 bytes from 172.16.28.1: seq=1 ttl=64 time=0.107 ms
```

**Comment by rbucker** [comment]
that was enough information for me.

*--Richard Bucker *

_http://about.me/richard.bucker http://about.me/richard.bucker_
