### ISSUE TITLE
what is the IP used in DNS when the container spans multiple networks?

### ISSUE THREAD

**Issue by rbucker** [monder/rkt-sidekick#4]
In one of my experiments to understand and test this project I had set `--net=container,default` and the DNS server had the wrong IP address.

**Comment by monder** [comment]
I suppose that has nothing to do with the sidekick :)
https://github.com/coreos/rkt/issues/2044#issuecomment-233390669 - rkt DNS discussion.
Please report all rkt/networking issues/questions to the corresponding repository.
